# Some config options here are taken from the docs for Equinox.
# See: https://github.com/patrick-kidger/equinox/blob/main/mkdocs.yml
# for an example of a project with lovely docs =)

site_name: "ocelot"
site_url: https://ocelot-docs.org
site_author: Emily Hunt
site_description: >-
   A toolbox for working with observations of star clusters.

repo_url: https://github.com/emilyhunt/ocelot
repo_name: ocelot

theme:
    name: material
    features:
        - navigation.sections  # Sections are included in the navigation on the left.
        # - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
        # - header.autohide  # header disappears as you scroll
        - search.suggest  # Suggested search
        - search.highlight
        - search.share
        - navigation.tabs  # Shows tabs instead of endless header list
        - navigation.tabs.sticky  # Tabs always visible
    palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
        # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
        - scheme: default
          primary: deep orange
          accent: amber
          toggle:
            icon: material/weather-night
            name: Switch to dark mode
        - scheme: slate
          primary: blue grey
          accent: deep orange
          toggle:
            icon: material/weather-sunny
            name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right
        logo: "material/lightbulb-outline"
    favicon: "_static/favicon.png"

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg


plugins:
    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    - social  # Makes a preview image for each page
    - mkdocstrings:
        handlers:
            python:
                options:
                    docstring_style: numpy  # Render docs as numpy style
                    show_source: true
                    show_root_heading: true
                    show_object_full_path: true
                    members_order: source
                    inherited_members: true  # Allow looking up inherited methods
    # - privacy  # Not installed error???


nav:
    - Getting Started: 
        - Overview: 'index.md'
        - Installation: 'wip.md'
        - Quick guide: 'wip.md'
        - Configuration: 'wip.md'
        - Citing ocelot: 'wip.md'
        - Further reading: 'wip.md'
        - Technical Stuff:
            - Changelog: 'wip.md'
            - Reporting an issue: 'wip.md'

    - Examples:
        - Star clusters in Gaia data:
            - Detect a star cluster in Gaia data: 'wip.md'
            - Crossmatching catalogues: 'wip.md'
        - Color-magnitude diagrams:
            - Work with PARSEC isochrones: 'wip.md'
            - Work with MIST isochrones: 'wip.md'
            - Fit an isochrone: 'wip.md'
        - Simulating clusters:
            - Simulate a star cluster from scratch: 'wip.md'
    - API Reference:
        - Calculate: 'api/calculate.md'
    - Contibute to ocelot!: 
        - Why ocelot?: 'developing.md'